apiVersion: apps/v1
kind: Deployment
metadata:
  name: myname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myname
  template:
    metadata:
      labels:
        app: myname
    spec:
      containers:
        - name: myname
          image: uk.icr.io/testeee/myrepo@sha256:de0288f67c1816204543ca9616270d02eb097a02ff12cfaa663a3b9d102b8d88
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    mylabelkey: mylabelvalue
spec:
  selector:
    app: myname
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31514

