server:
  port: 8080
spring:
#  transaction:
#    rollback-on-commit-failure: true
  thymeleaf:
    #TODO: close when developing, open when online
    cache: false
  profiles:
    #TODO remove the 1 1 test data in admins
    include: datasource

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.uclibm.ixn.domain

spring.servlet.multipart.max-file-size: 2MB
spring.servlet.multipart.max-request-size: 2MB

