server:
  port: 8080
spring:
  thymeleaf:
    #TODO: close when developing, open when online
    cache: false
  profiles:
    # the datasource and watson are not pushed to github as they contain credentials
    include: datasource,watson

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.uclibm.ixn.domain
logging:
  file:
    path:
